In [5]:
import numpy as np

Lists with % of low emission Licensed Taxis operating in York and Leeds per year from 2011 to 2019

In [6]:
yorkTaxis = [0.00,1.00,3.00,6.00,8.00,13.00,16.10,17.60,19.90]
leedsTaxis=[0.50,1.20,2.30,5.00,7.80,14.30,17.10,17.30,20.90]

Converting the lists into arrays

In [7]:
york=np.array(yorkTaxis)
leeds=np.array(leedsTaxis)

Printing the shape of the arrays

In [8]:
print(york.shape)
print(leeds.shape)

(9,)
(9,)


Printing the data types of the arrays

In [9]:
print(york.dtype)
print(leeds.dtype)

float64
float64


Getting the values of York and Leeds from 2015 until 2019

In [10]:
print(york[4:])
print(leeds[4:])

[ 8.  13.  16.1 17.6 19.9]
[ 7.8 14.3 17.1 17.3 20.9]


Finding the min, max and mean of each city

In [11]:
yorkMin=np.min(york)
yorkMax=np.max(york)
yorkMean=np.mean(york)
print(yorkMin,yorkMax,yorkMean)

leedsMin=np.min(leeds)
leedsMax=np.max(leeds)
leedsMean=np.mean(leeds)
print(leedsMin,leedsMax,leedsMean)

0.0 19.9 9.399999999999999
0.5 20.9 9.600000000000001


Concatenating the two arrays

In [12]:
allData=np.concatenate((york,leeds))
print(allData)

[ 0.   1.   3.   6.   8.  13.  16.1 17.6 19.9  0.5  1.2  2.3  5.   7.8
 14.3 17.1 17.3 20.9]


Sorting the concatenated array

In [13]:
sortedAllData=np.sort(allData)
print(sortedAllData)

[ 0.   0.5  1.   1.2  2.3  3.   5.   6.   7.8  8.  13.  14.3 16.1 17.1
 17.3 17.6 19.9 20.9]


Transforming the concatenated array into a 2D array where each column holds values for each city

In [14]:
allData2D=allData.reshape(9,2)
print(allData2D)

[[ 0.   1. ]
 [ 3.   6. ]
 [ 8.  13. ]
 [16.1 17.6]
 [19.9  0.5]
 [ 1.2  2.3]
 [ 5.   7.8]
 [14.3 17.1]
 [17.3 20.9]]


Transposing the allData2D array

In [15]:
print(allData2D.T)

[[ 0.   3.   8.  16.1 19.9  1.2  5.  14.3 17.3]
 [ 1.   6.  13.  17.6  0.5  2.3  7.8 17.1 20.9]]


Finding the difference in % of low emission licensed taxis between York and Leeds each year

In [16]:
diff = np.subtract(york,leeds)
print(diff)

[-0.5 -0.2  0.7  1.   0.2 -1.3 -1.   0.3 -1. ]


A function that returns the min and max value of the differences

In [17]:
def minMaxDiff(diff):
    return (np.min(diff),np.max(diff))

print(minMaxDiff(diff))

(-1.3000000000000007, 1.0)


A function that counts how many years York had taxis with lower emissions than Leeds

In [18]:
def countEmissions(a):
    return np.count_nonzero(a<0)

print(countEmissions(diff))

5


Creating a 2D array in which each entry from the york array is associated with its year

In [36]:
data = np.vstack((np.arange(2011,2020,1),york))

print(data)

[[2011.  2012.  2013.  2014.  2015.  2016.  2017.  2018.  2019. ]
 [   0.     1.     3.     6.     8.    13.    16.1   17.6   19.9]]
